import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../../styles/colors';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  transContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: Colors.black + '77',
  },
  orderDate: {
    backgroundColor: Colors.background,
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: 24,
    borderRadius: 24,
  },
  orderDateTitle: {
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: 32,
    fontFamily: 'Montserrat-Bold',
  },
  orderDateLabel: { fontWeight: '600', marginBottom: 8, fontFamily: 'Montserrat-Bold' },
  orderDateInputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  orderDateInput: { width: '48%', height: 56 },
  orderDateFabView: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
  },
  bold: {
    fontFamily: 'Montserrat-Bold',
    fontWeight: Platform.OS === 'ios' ? '700' : '600',
  },
  orderDateFab: { backgroundColor: Colors.primary, borderRadius: 8 },
  mb16: { marginBottom: 16 },
  mt16: { marginTop: 16 },
  picker: {
    inputIOS: {
      borderWidth: 1,
      borderColor: Colors.grey,
      borderRadius: 6,
      fontSize: 16,
      height: 56,
      paddingHorizontal: 12,
      backgroundColor: Colors.onPrimary,
      fontFamily: 'Montserrat',
      color: Colors.black,
    },
    inputAndroid: {
      borderWidth: 1,
      borderColor: Colors.grey,
      borderRadius: 6,
      fontSize: 16,
      height: 56,
      paddingHorizontal: 12,
      backgroundColor: Colors.onPrimary,
      fontFamily: 'Montserrat',
      color: Colors.black,
    },
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: { fontWeight: '600', color: Colors.onPrimaryContainer, fontFamily: 'Montserrat-Bold' },
  p16: { padding: 16 },
  rate: { alignItems: 'flex-end', paddingHorizontal: 8, marginBottom: 8 },
  totalBtn: {
    width: '100%',
    marginTop: 48,
    backgroundColor: Colors.background,
  },
  bordered: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: Colors.grey + '50',
  },
  map: {
    width: '100%',
    height: 180,
    borderRadius: 8,
  },
  paymentRow: { flexDirection: 'row', alignItems: 'center' },
  dateSummary: { marginLeft: 4, flex: 1 },
  safety: {
    backgroundColor: Colors.secondary,
    height: 120,
    borderRadius: 16,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 24,
  },
  safetyImage: { height: 150, width: 100 },
  mapBg: {
    minHeight: '100%',
    width: '100%',
    justifyContent: 'flex-end',
  },
  arrow: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 4,
  },
  closeFabContainer: {
    position: 'absolute',
    flexDirection: 'row',
  },
  closeFab: {
    backgroundColor: Colors.white,
    borderRadius: 8,
    marginLeft: 16,
  },
  rowed: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  livefeedAction: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatInputBg: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 8,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderColor: Colors.grey + '50',
    borderStyle: 'solid',
  },
  chatInput: { minHeight: 56 },
  text: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginVertical: 4,
    borderRadius: 16,
  },
  sender: {
    backgroundColor: Colors.secondary,
    color: Colors.onSecondary,
  },
  receiver: {
    backgroundColor: Colors.primaryContainer,
    color: Colors.onPrimaryContainer,
  },
  chatDate: { color: Colors.grey, textAlign: 'center' },
  chatAvatar: { marginRight: 4, marginTop: 6 },
  chatRow: { flexDirection: 'row', justifyContent: 'flex-end' },
  comment: { height: 112 },
  mx_auto: { marginLeft: 'auto', marginRight: 'auto' },
  mb8: { marginBottom: 8 },
});
